# Compose file for the webapp
#
# Be sure to set environment variable in app.conf and then run
# `$ source $PATH/app.conf`
#
# To build and run:
#    docker-compose up

version: "3"

services:

  neo4j:
    env_file: .env
    image: neo4j
    ports:
      - "7474:7474" # bolt web admin
    # only uncomment for development builds
      - "7687:7687" 
    expose:
      - "7687" # bolt connection
    environment:
      - NEO4J_AUTH=none
    volumes:
      - "neo4j:/var/lib/neo4j/data"

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - "data:/data/db"

  node_webapp:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile.app
    ports:
      - "${PORT}:80"

  loc_data_miner:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.loc
    volumes:
      - "loc:/usr/src/loc"
  
  worldcat_data_miner:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.worldcat

volumes:
  data:
  neo4j:
  loc: